######################
# book (meta) info

title: Azrieli Students On Software Modeling and Architecture
author: 
  name: @robi-y

github:
  url: "https://github.com/jce-il/ASOSA"


########
# more settings
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true # Auto-generate ID's for headings
  
collections:
  chapters:
      output: false

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

